# 将html生成文件
import asyncio
from pathlib import Path
import json
from playwright.async_api import async_playwright

from typing import AsyncGenerator, List, Dict
from typing_extensions import override

from google.genai.types import Content
from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Blob

from src.logger import logger
from src.agents.experts.ppt_v2.tool_image import html_to_image
from src.agents.experts.ppt_v2.tool_pptx import html_to_pptx
from src.utils import clean_json_string

class HTMLToImageAndPPTXAgent(BaseAgent):
    """
    a custom agent for search image or text
    """

    model_config = {"arbitrary_types_allowed": True}

    def __init__(
            self,
            name: str,
            description: str = ""
    ):
        super().__init__(
            name=name,
            description=description
        )


    def format_event(self, content_text: str = None, state_delta: Dict = None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Runs the HTMLTOImage asynchronously.
        This method achieves transform html page to a single image.
        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """

        # current_parameters = ctx.session.state.get('current_parameters', {})
        ppt_final_result = ctx.session.state.get('ppt_generation/final_results', '')
        logger.info(ppt_final_result)

        ppt_final_result = clean_json_string(ppt_final_result)
        ppt_final_result_json = json.loads(ppt_final_result)
        html_code_all_pages = None
        html_code_single = None
        create_js = None
        if 'ppt_html_code_all_pages' in ppt_final_result_json:
            html_code_all_pages = ppt_final_result_json['ppt_html_code_all_pages']
        if 'ppt_html_code_single_page' in ppt_final_result_json:
            html_code_single = ppt_final_result_json['ppt_html_code_single_page']
        if 'create_js' in ppt_final_result_json:
            create_js = ppt_final_result_json['create_js']

        if isinstance(create_js, str) and len(create_js) > 7:
            if create_js[:7] == '```json':
                create_js = create_js[7:]
                create_js = create_js.strip('`')
            elif create_js[:5] == '```js':
                create_js = create_js[5:]
                create_js = create_js.strip('`')


        suggested_width = 1024
        suggested_height = 768
        if 'suggested_width' in ppt_final_result_json:
            suggested_width = ppt_final_result_json['suggested_width']
        if 'suggested_height' in ppt_final_result_json:
            suggested_height = ppt_final_result_json['suggested_height']

        input_img_name = ppt_final_result_json.get('ppt_image_name_list', [])  # TODO：需要强调填充

        img_binary_list = []
        logger.info(input_img_name)
        for name in input_img_name:
            art_part = await ctx.artifact_service.load_artifact(filename=name, app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id)
            if art_part is not None:
                img_binary_list.append((name, art_part.inline_data.data)) # TODO: bug,需要确保name 是在artifact中。
        image_result = await html_to_image(html_code_all_pages, img_binary_list, suggested_width, suggested_height)

        pptx_result = await html_to_pptx(html_code_all_pages, html_code_single, img_binary_list, create_js)

        # logger.info(result)
        step = ctx.session.state['step']
        if image_result["status"] == "error":
            error_text = f"执行步骤{step + 1}: {self.name}执行出错：{image_result['message']}"
            message_for_user = f"执行步骤执行出错：{image_result['message']}"
            current_output = {"author": self.name, "status": "error", "message": error_text, 'message_for_user': message_for_user, 'output_text':''}

            logger.error(error_text)
            yield self.format_event(error_text, {"current_output": current_output})
            return

        if pptx_result["status"] == "error":
            error_text = f"执行步骤{step + 1}: {self.name}执行出错：{pptx_result['message']}"
            message_for_user = f"执行步骤执行出错：{pptx_result['message']}"
            current_output = {"author": self.name, "status": "error", "message": error_text, 'message_for_user': message_for_user, 'output_text':''}

            logger.error(error_text)
            yield self.format_event(error_text, {"current_output": current_output})
            return


        # 保存图像文件
        text = f"执行步骤{step + 1}: {self.name}：从ppt转图片完成"
        message_for_user = "执行步骤从ppt转图片完成"
        output_artifacts = []

        artifact_name = f"step{ctx.session.state.get('step') + 1}_ppt_html2img_output.png"
        artifact_part = Part(inline_data=Blob(mime_type='image/png', data=image_result['message']))

        await ctx.artifact_service.save_artifact(
            app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id,
            filename=artifact_name, artifact=artifact_part
        )

        text += f"\nppt_html2img图片保存成功，输出图片名称为{artifact_name}"
        description = f"ppt_html文件转换得到的图片。\nppt_html_code：{html_code_all_pages}\n\n"

        output_artifacts.append({'name': artifact_name, 'description': description})

        # 保存pptx文件
        text = text +  f"执行步骤{step + 1}: {self.name}：从html转pptx完成"
        message_for_user = message_for_user + "执行步骤转pptx完成"

        artifact_name = f"step{ctx.session.state.get('step') + 1}_ppt_output.pptx"
        artifact_part = Part(inline_data=Blob(mime_type='application/vnd.openxmlformats-officedocument.presentationml.presentation', data=pptx_result['message']))

        await ctx.artifact_service.save_artifact(
            app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id,
            filename=artifact_name, artifact=artifact_part
        )

        text += f"\nppt保存成功，输出文件名称为{artifact_name}"
        description = f"ppt_html文件转换得到的pptx文件。\nppt_html_code：{html_code_single}\n\n"

        output_artifacts.append({'name': artifact_name, 'description': description})

        # 输出event
        current_output = {"author": self.name,
            "status": "success",
            "message": text,
            "message_for_user": message_for_user,
            "output_artifacts": output_artifacts,
            'output_text':''
        }
        yield self.format_event(text, {'current_output': current_output})
        return








