import asyncio
from pathlib import Path

import os
import sys
import os.path
import tempfile
import json
import subprocess

import shutil
from pathlib import Path

from playwright.async_api import async_playwright
from typing import AsyncGenerator, List, Dict
from typing_extensions import override

from google.genai.types import Content
from google.adk.agents import BaseAgent, LlmAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event, EventActions
from google.adk.tools import ToolContext
from google.genai.types import Part, Blob

from src.logger import logger
from src.utils import clean_json_string

async def run_render_video(workdir, code_path, scene_name):
    # env_result_1 = subprocess.run(["npm", "init", "-y"],  capture_output=True,cwd=workdir, text=True)
    # env_result_2 = subprocess.run(["npm", "install", "pptxgenjs", "playwright", "sharp"], capture_output=True, cwd=workdir, text=True)
    # env_result_3 = subprocess.run(["npx", "playwright", "install", "chromium"], capture_output=True, cwd=workdir, text=True)

    result = subprocess.run(
        ["manim", "-ql", code_path, scene_name],
        capture_output=True,
        cwd=workdir,
        text=True
    )

    return {
        "ok": result.returncode == 0 ,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "code": str(result.returncode)
    }


async def manim_to_video(manim_code: str, scene_name:str):

    td =  tempfile.TemporaryDirectory().name
    os.makedirs(td, exist_ok=True)
    logger.info('~~~~~~')
    logger.info(td)

    manim_code_save_path = os.path.join(td,  'manim.py')
    with open(manim_code_save_path, "w", encoding="utf-8") as fh:
        fh.write(manim_code)

    result = await run_render_video(td, 'manim.py', scene_name)
    logger.info(result)
    video_bin = None
    if not result['ok']:
        error_message = result['stdout'] + '\n' + result['stderr'] + '\n' + result['code']
    else:
        mp4_files = []

        for root, dirs, files in os.walk(td):
            for file in files:
                if file.lower().endswith(".mp4"):
                    full_path = os.path.abspath(os.path.join(root, file))
                    if 'partial_movie_files' not in full_path: # partial_movie_files 文件夹下放的是临时文件
                        mp4_files.append(full_path)

        # pptx_files 的长度应该是1
        if len(mp4_files) > 0:
            mp4_result = mp4_files[0]
            with open(mp4_result, 'rb') as f:
                video_bin = f.read()
        else:
            error_message = "mp4 文件生成失败"



    if video_bin is not None:
        result = {"status": "success", "message": video_bin}
    else:
        result = {"status": "error", "message": error_message}

    return result

class RenderAgent(BaseAgent):

    model_config = {"arbitrary_types_allowed": True}

    def __init__(
            self,
            name: str,
            description: str = ""
    ):
        super().__init__(
            name=name,
            description=description
        )


    def format_event(self, content_text: str = None, state_delta: Dict = None):
        event = Event(author=self.name)
        if state_delta:
            event.actions = EventActions(state_delta=state_delta)
        if content_text:
            event.content = Content(role='model', parts=[Part(text=content_text)])
        return event


    @override
    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        """Runs the HTMLTOImage asynchronously.
        This method achieves transform html page to a single image.
        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the image generation process.
        """

        current_parameters = ctx.session.state.get('current_parameters', {})
        manim_result_by_agent = ctx.session.state.get('math_video/manim_code', '') # 来自html_generation的结果

        logger.info(manim_result_by_agent)

        try:
            manim_result_by_agent = clean_json_string(manim_result_by_agent)
            manim_result = json.loads(manim_result_by_agent)
        except Exception as e:
            current_output = {"author": self.name,
                "status": "success",
                "message": '获取代码错误',
                "message_for_user": '视频生成失败' + str(e),
                'output_text':''
            }
            text = f"\nmanim2video 视频生成失败。"
            yield self.format_event(text, {'current_output': current_output})
            return


        manim_code = manim_result['manim_code']
        scene_name = manim_result['scene_name']


        logger.info(manim_code)


        result = await manim_to_video(manim_code, scene_name)

        # logger.info(result)
        step = ctx.session.state['step']
        if result["status"] == "error":
            error_text = f"执行步骤{step + 1}: {self.name}执行出错：{result['message']}"
            message_for_user = f"执行步骤执行出错：{result['message']}"
            current_output = {"author": self.name, "status": "error", "message": error_text, 'message_for_user': message_for_user, 'output_text':''}

            logger.error(error_text)
            yield self.format_event(error_text, {"current_output": current_output})
            return

        else:
            # 保存文件
            text = f"执行步骤{step + 1}: {self.name}：从 manim 转视频完成"
            message_for_user = "执行步骤从 manim 转视频完成"
            output_artifacts = []

            artifact_name = f"step{ctx.session.state.get('step') + 1}_manim2video_output.mp4"
            artifact_part = Part(inline_data=Blob(mime_type='video/mp4', data=result['message']))

            await ctx.artifact_service.save_artifact(
                app_name=ctx.session.app_name, user_id=ctx.session.user_id, session_id=ctx.session.id,
                filename=artifact_name, artifact=artifact_part
            )

            text += f"\nmanim2video 视频保存成功，输出视频名称为{artifact_name}"
            description = f"manim文件转换得到的视频。\nmanim_code：{manim_code}\n\n"

            output_artifacts.append({'name': artifact_name, 'description': description})

            # 输出event
            current_output = {"author": self.name,
                "status": "success",
                "message": text,
                "message_for_user": message_for_user,
                "output_artifacts": output_artifacts,
                'output_text':''
            }
            yield self.format_event(text, {'current_output': current_output})
            return








