import datetime
import json, uuid
import re
import os.path
from typing import AsyncGenerator, List, Optional, Any, Dict, Tuple


from google.adk.agents import BaseAgent, LlmAgent
from google.adk.models.lite_llm import LiteLlm
from google.adk.agents.invocation_context import InvocationContext
from google.adk.artifacts import InMemoryArtifactService
from google.adk.events import Event, EventActions
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai.types import Content, Part, Blob

from src.logger import logger
from src.llm.model_factory import build_model_kwargs
from conf.system import SYS_CONFIG
from conf.agent import experts_list
from src.utils import database_op_with_retry

available_agents: str = '\n'.join([str(expert) for expert in experts_list if expert.enable])
time_str = datetime.date.today().strftime("%Y-%m-%d")

def clean_and_parse_json(json_string: str) -> Dict[str, Any]:
    cleaned_string = re.sub(r'^```(json)?\s*|\s*```$', '', json_string.strip(), flags=re.MULTILINE)
    try:
        return json.loads(cleaned_string)
    except json.JSONDecodeError:
        logger.error(f"JSON解析失败，原始字符串: '{json_string}'")
        return {}
    
class ExecutorAgent(BaseAgent):
    """
    The executor agent that generate plan
    """
    planner: LlmAgent
    executor_replan_enabled: bool

    def __init__(
        self,
        name:str,
        description:str,
        llm_model: str = '',
        executor_replan_enabled: bool = False,
    ):
        if not llm_model:
            llm_model = SYS_CONFIG.executor_llm_model
        logger.info(f"ExecutorAgent: using llm: {llm_model}")

        model_kwargs = build_model_kwargs(llm_model)

        planner = LlmAgent(
            name="PlannerAgent",
            **model_kwargs,
            description='Analyze input request, output a plan in json format in order to successive execution.',
            instruction=EXECUTOR_INSTRUCTION + available_agents + '\n\n'
        )

        super().__init__(
            name=name,
            description=description,
            planner = planner,
            executor_replan_enabled = executor_replan_enabled
        )

        

    async def _run_async_impl(
        self, ctx: InvocationContext
    ) -> AsyncGenerator[Event, None]:
        """Run the executor agent
        if self.executor_replan_enabled==True: executor will generate a plan on itself
        otherwise, it directly use the plan stored in state

        Args:
            ctx (InvocationContext): The invocation context for the agent.
        Yields:
            Event: The events generated by the sequential agent during the plan generation process.

        """
        
        async for event in self.planner.run_async(ctx):
            if event.is_final_response() and event.content and event.content.parts:
                final_response_text = ''
                text_part = next((part.text for part in event.content.parts if part.text), None)
                if text_part:
                    final_response_text = text_part

                # new plan generated by executor agent
                plan = clean_and_parse_json(final_response_text)

                if 'next_agent' in plan and 'parameters' in plan:
                    # yield Event(author='api_server', content=None, actions=EventActions(state_delta=plan))
                    yield Event(author='api_server', content=None, actions=EventActions(state_delta={"current_plan": plan}))


class Executor:
    def __init__(
        self,
        session_service: InMemorySessionService,
        artifact_service: InMemoryArtifactService,
        app_name: str = SYS_CONFIG.app_name,
        save_dir: str = '',
        uid: str = '',
        sid: str = '',
        username: str = '',
        llm_model: str = '',
        expert_runners: Dict[str, Runner] = {}, # 用于运行expert的runner
        executor_replan_enabled: bool = False
    ) -> None:
        self.app_name = app_name
        self.session_service = session_service
        self.artifact_service = artifact_service
        self.save_dir = save_dir
        self.uid = uid
        self.sid = sid
        self.username = username
        self.executor_replan_enabled = executor_replan_enabled

        if not llm_model:
            llm_model = SYS_CONFIG.executor_llm_model
        logger.info(f"ExecutorAgent: using llm: {llm_model}")

        self.expert_runners = expert_runners

        self.executor_agent = ExecutorAgent(
            name="ExecutorAgent",
            description="",
            llm_model=llm_model,
            executor_replan_enabled=executor_replan_enabled
        )

        self.executor_runner = Runner(agent=self.executor_agent, app_name=self.app_name, session_service=self.session_service, artifact_service=self.artifact_service)

    async def run_agent_and_log_events(self, runner: Runner, user_id: str, session_id: str, new_message: Optional[Content] = None) -> str:
        final_response_text = ""
        async for event in runner.run_async(user_id=user_id, session_id=session_id, new_message=new_message): # 这个是那个agent运行的？
            logger.debug(f"Event: {event.model_dump_json(indent=2, exclude_none=True)}")
            if event.is_final_response() and event.content and event.content.parts:
                text_part = next((part.text for part in event.content.parts if part.text), None)
                if text_part:
                    final_response_text = text_part
                    logger.info(f"[{runner.agent.name}] 最终响应文本: '{final_response_text}'")
        return final_response_text
    
    async def add_event(self, text:str='', state_delta:Dict=None):
        if state_delta is None:
            state_delta = {}

        if text:
            event = Event(
                author='api_server',   # TODO: 确认author是否合理
                content=Content(role='model', parts=[Part(text=text)]),
                actions=EventActions(state_delta=state_delta)
            )
        else:
            event = Event(
                author='api_server',
                actions=EventActions(state_delta=state_delta)
            )

        current_session = await database_op_with_retry(
                self.session_service.get_session,
                app_name=SYS_CONFIG.app_name,
                user_id=self.uid,
                session_id=self.sid,
            )

        # await self.session_service.append_event(current_session, event) # TODO: 确定作用域
        # 使用带重试的写入，防止数据库锁定失败
        await database_op_with_retry(
            self.session_service.append_event,
            session=current_session,
            event=event,
            logger=logger,
            op_name="add_event_append_event"
        )

    async def save_artifact(self, art_name: str, current_uid:str, current_sid:str):
        art_part = await self.artifact_service.load_artifact(
            app_name=self.app_name, user_id=self.uid, session_id=self.sid, filename=art_name
        )

        if art_part is not None:
            art_name = f"{current_uid}_{current_sid}_{art_name}"
            art_path = os.path.join(self.save_dir, art_name)
            with open(art_path, mode='wb') as f:
                f.write(art_part.inline_data.data)
        else:
            logger.error(f'load {art_name} return none and save failed') # TODO: 确定原因
            return None
        return art_path
    
    async def check_paramters_valid(self, agent_name: str, params_for_expert: Dict[str, Any]) -> str:
        error_text = ''
        error_arifact_names = []

        # 检查调用的agent名称是否在提供的expert_runners中
        if agent_name not in self.expert_runners:
            error_text = f"Executor决策了未知的Agent: '{agent_name}'，它不在提供的agent列表中"
            return error_text

        # 检查调用的artifact名称是否存在于artifact service中
        if 'input_name' in params_for_expert:
            art_list = await self.artifact_service.list_artifact_keys(
                app_name=self.app_name, user_id=self.uid, session_id=self.sid
            )

            input_names = []
            if isinstance(params_for_expert['input_name'], str):
                input_names = [params_for_expert['input_name']]
            elif isinstance(params_for_expert['input_name'], list):
                input_names = params_for_expert['input_name']
            else:
                error_text += f"当前的规划中的parameters['input_name']格式错误，需要为string或list"
                return error_text

            for name in input_names:
                if name in art_list:
                    continue

                logger.info(art_list)
                error_arifact_names.append(name)

        if len(error_arifact_names) > 0:
            all_artifact_names = ', '.join(error_arifact_names)
            error_text += f"Executor选择了未知的 artifact: {all_artifact_names}，它们不在artifacts列表中"

        return error_text

    async def execute_plan(self):
        """
        执行plan函数，直接从主session的state中的 `current_plan` 字段读取当前规划的参数并执行
        """
        if self.executor_replan_enabled: # 使用自己的llm为当前的规划生成精确的调用参数（通常不使用，因为我们已经指定规划agent生成精确参数）
            new_message = Content(role='user', parts=[Part(
                text="根据原始任务和当前state，生成下一步的操作步骤。如果之前生成了整个任务所有步骤的规划，请忽略。你只需要关注整体任务和当前的state。")])  # TODO: 确定new_message是否合理
            await self.run_agent_and_log_events(self.executor_runner, session_id=self.sid, user_id=self.uid, new_message=new_message) #

        # load state['current_plan']
        current_session = await database_op_with_retry(
                self.session_service.get_session,
                app_name=SYS_CONFIG.app_name,
                user_id=self.uid,
                session_id=self.sid,
            )

        # TODO: 有潜在问题，使用完之后没有清空。如果当前 next_agent 决策没有填充这个字段的话，会继续执行上一个步骤。
        # 增加这个todo，在最后面执行完之后清空 current_plan，使用state_delta进行覆盖
        plan = current_session.state.get('current_plan') 

        next_agent_name = plan.get("next_agent")
        params_for_expert = plan.get("parameters", {})
        final_summary = plan.get("summary", {})

        # 检查参数有效性
        error_text = await self.check_paramters_valid(next_agent_name, params_for_expert)
        # 如果参数有问题，那么error_text会有值
        if error_text:
            logger.error(error_text)
            
            # 2026.1.12之前版本出错后没有更新state delta，这里会有相应更新，是否正确需要确认？？？

            # 2026.1.12之前版本遇到错误会直接返回None，鲁棒性不强，外层函数判断麻烦，这里改成统一的。
            # 这里author直接使用Executor，因为没有执行expert agent
            current_output = {
                "author": "Executor",
                "status": "error",
                "message": error_text,
                "output_artifacts": [],
                "output_text": ""
            }
        else:
            # 参数没有问题，运行expert agent
            # 将当前的参数写入state
            await self.add_event(state_delta={'current_parameters': params_for_expert})
            # 运行expert，运行的结果位于state['current_output']
            expert_runner = self.expert_runners[next_agent_name]
            new_message = Content(role='user', parts=[Part(text="根据原始任务和当前的plan以及对应的输入参数，调用对应的agent来执行")]) # TODO: 没有author，确认
            await self.run_agent_and_log_events(expert_runner, user_id=self.uid, session_id=self.sid, new_message=new_message) # 调用这个runner下的agent。TODO: 这个message 在 llm_request 里面没有author
            current_output = {} # 先置空，下面会从state中读取

        # 完成运行后，把信息写入state
        # 专家agent的输出：state['current_output']
        # 所有专家agent的输出结构：
        # {
        #     "author": 专家agent名称
        #     "status": 执行成功或失败
        #     "message": 执行日志输出
        #     "output_artifact": 输出图片信息：list[dict]，每个dict包含{'name', 'description'}
        #     "output_text": 输出文本信息：str
        # }

        # todo: 专家输出使用统一对象进行封装，而不是靠注释规范，zyh

        current_session = await database_op_with_retry(
                self.session_service.get_session,
                app_name=SYS_CONFIG.app_name,
                user_id=self.uid,
                session_id=self.sid,
            )
        # 如果上面expert运行了，current_output会被设置，从state中读取
        if not current_output:
            current_output = current_session.state.get('current_output')
        
        current_step = current_session.state.get('step')
        artifacts_history = current_session.state.get('artifacts_history')
        text_history = current_session.state.get('text_history')
        message_history = current_session.state.get('message_history')
        summary_history = current_session.state.get('summary_history')

        # 对于pending状态，是否需要特殊处理？
        if not current_output:
            current_output = {'status': 'pending'}

        state_delta = {
            'step': current_step + 1,
            'current_plan': {},  # 清空当前的plan，防止重复执行
        }

        # 把新生成的artifact保存到本地
        if current_output['status'] == 'success' and 'output_artifacts' in current_output:
            for art in current_output['output_artifacts']:
                current_sid = current_session.state['sid']
                current_uid = current_session.state['uid']
                logger.info(f"saving artifact {art['name']}")
                art_path = await self.save_artifact(art['name'], current_uid, current_sid)
                art['path'] = art_path

                logger.info(f"saved to {art_path}")

        # 设置event保存到session中
        if current_output['status'] == 'success':
            # 保存output_artifacts和artifacts_history
            if 'output_artifacts' in current_output:
                state_delta['new_artifacts'] = current_output['output_artifacts']
                state_delta['artifacts_history'] = artifacts_history + [current_output['output_artifacts']] # 这里保存的是文本： name、description 。
            else:
                state_delta['new_artifacts'] = []
                state_delta['artifacts_history'] = artifacts_history + [[]]

            # 保存text_history
            if 'output_text' in current_output and len(current_output['output_text']) > 0:
                state_delta['text_history'] = text_history + [current_output['author'] + '的 output_text: \n' + str(current_output['output_text']) + '\n']
            else:
                state_delta['text_history'] = text_history + [None]

            # 保存summary_history
            state_delta['summary_history'] = summary_history + [final_summary]

            # 保存message_history
            state_delta['message_history'] = message_history + [current_output['message']]

            await self.add_event(text=f"第{current_step+1}轮执行已完成。这一步的原始目标：`{final_summary}`，执行完成后的总结：`{current_output['message']}`", state_delta=state_delta)

        elif current_output['status'] == 'error':
            state_delta['new_artifacts'] = []
            state_delta['artifacts_history'] = artifacts_history + [[]]
            state_delta['text_history'] = text_history + [None]
            state_delta['message_history'] = message_history + [current_output['message']]
            state_delta['summary_history'] = summary_history + [final_summary]

            await self.add_event(text=f"第{current_step+1}轮专家执行出错。这一步的原始目标：`{final_summary}`, 执行错误描述：`{current_output['message']}`。当前步骤目标可能未完成，需要视情况重新执行或使用新的参数或方法。", state_delta=state_delta)

        return current_output


EXECUTOR_INSTRUCTION = """
你是一个复杂任务的执行AI。你的任务是在一个循环中持续分析一个共享的“状态(state)”，并决定下一步需要调用哪个专家Agent以及参数，直到整个多步骤的用户任务完成。

**你需要查看对话历史和state中的参数来了解当前的任务规划和状态
之前生成的全局所有步骤规划如下，它可能存在也可能不存在：{global_plan}


**你的唯一输出必须是一个JSON对象。**
**JSON 输出格式:**
```json
{{
    "next_agent": "AgentName",
    "parameters": {{
    "param1_for_agent": "value1"
    }},
    "summary": "对你当前决策的简短总结，会展示给用户。"
}}
```

# 关键指令:
1.  **发出结束信号**: 当输出单步规划时且你判断整个用户的初始任务已经彻底完成时，你必须将 `next_agent` 的值设置为 `null` 或 `"FINISH"`。这是终止循环的唯一方式。
2.  **利用中间产物**: 你必须检查其他Agent生成的输出文件路径（路径中通常包含'output'），之前步骤的对话内容中会包含文件输出名称，使用这些输出来准备下一步的参数。
3.  **精确任务分派**: 对于图像编辑，要特别注意用户的意图。如果用户提到“修复”、“替换特定区域”、“移除某个物体”或提供了蒙版图，你应该使用专门的局部重绘功能。

# 工作流程:

1.  **分析当前状态**:
    - 仔细阅读 `{user_prompt}`以及当前的任务规划，来理解当前任务的执行情况。

2.  **决策与参数准备**:
    - 如果任务未完成，决定下一步需要哪个专家。
    - 为该专家准备一个包含所有必需参数的 `parameters` 字典。


 
# 沟通语言
 - 需要显示给用户看的信息以及中间思考过程，请使用使用用户的语言类型。

# 你可以使用的专家 Agent 列表和所需参数: \n
"""


